import logging
from typing import Any, Dict

from app.models.analysis import Analysis
from app.models.job_attempt import JobAttempt

logger = logging.getLogger(__name__)


class FixtureProcessor:
    """Deterministic, synthetic fixture processor purely to prove asynchronous orchestration.

    Per rules.md:
    - Never fabricate observations. Synthetic fixtures must be unmistakably labeled.
    - Persisted method_version is explicitly stamped 'fixture-orchestration-v0'.
    """

    METHOD_VERSION = "fixture-orchestration-v0"

    def process_layer(
        self,
        analysis: Analysis,
        attempt: JobAttempt,
        layer_type: str,
    ) -> Dict[str, Any]:
        logger.info(
            "Executing deterministic fixture processor for layer '%s' (analysis_id=%s, attempt_id=%s)",
            layer_type,
            analysis.id,
            attempt.id,
            extra={
                "analysis_id": str(analysis.id),
                "attempt_id": str(attempt.id),
                "synthetic": True,
            },
        )

        return {
            "status": "ready",
            "quality_label": "synthetic_fixture",
            "method_version": self.METHOD_VERSION,
            "metrics": {
                "synthetic_execution": True,
                "layer_type": layer_type,
                "note": "Deterministic fixture output purely proving asynchronous orchestration pipeline.",
            },
            "provenance": {
                "source": "fixture_orchestration_v0",
                "synthetic": True,
                "attribution": "Synthetic fixture — not real observations",
            },
            "warnings": [
                "DEMONSTRATIONDATA: Output generated by deterministic test fixture, not satellite observations."
            ],
        }
