import {
  ProtectedArea,
  ChangeEventHotspot,
  FireHotspot,
  WildlifeOccurrence,
  AlertNotification,
  ReportItem,
  TimelineDataPoint
} from '@/types';

export const MOCK_AREAS: ProtectedArea[] = [
  {
    id: 'area-1',
    wdpa_id: 'WDPA-755',
    name: 'Serengeti National Park',
    designation: 'National Park & World Heritage',
    protected_area_type: 'National Park (IUCN Category II)',
    iucn_category: 'II',
    country: 'Tanzania',
    country_code: 'TZ',
    state: 'Mara & Simiyu Regions',
    area_km2: 14763,
    total_hectares: 1476300,
    coordinates: { lat: -2.3333, lon: 34.8333 },
    forest_cover_percent: 74.2,
    canopy_loss_year_ha: 142.8,
    active_fires_count: 6,
    threat_index: 38,
    biome: 'Tropical & Subtropical Grasslands, Savannas',
    last_analyzed: '2026-09-17T18:30:00Z',
  },
  {
    id: 'area-2',
    wdpa_id: 'WDPA-1240',
    name: 'Kaziranga National Park',
    designation: 'Tiger Reserve & World Heritage',
    protected_area_type: 'National Park & Tiger Reserve',
    iucn_category: 'II',
    country: 'India',
    country_code: 'IN',
    state: 'Assam',
    area_km2: 858,
    total_hectares: 85800,
    coordinates: { lat: 26.5775, lon: 93.1711 },
    forest_cover_percent: 68.5,
    canopy_loss_year_ha: 49.3,
    active_fires_count: 1,
    threat_index: 45,
    biome: 'Brahmaputra Valley Semi-Evergreen & Floodplain',
    last_analyzed: '2026-09-18T01:15:00Z',
  },
  {
    id: 'area-3',
    wdpa_id: 'WDPA-3294',
    name: 'Yasuní National Park',
    designation: 'Biosphere Reserve',
    protected_area_type: 'National Park & UNESCO Biosphere Reserve',
    iucn_category: 'II',
    country: 'Ecuador',
    country_code: 'EC',
    state: 'Orellana & Pastaza Provinces',
    area_km2: 9823,
    total_hectares: 982300,
    coordinates: { lat: -0.9997, lon: -75.9995 },
    forest_cover_percent: 91.4,
    canopy_loss_year_ha: 312.6,
    active_fires_count: 14,
    threat_index: 68,
    biome: 'Amazonian Moist Lowland Rainforest',
    last_analyzed: '2026-09-17T22:45:00Z',
  },
  {
    id: 'area-4',
    wdpa_id: 'WDPA-1982',
    name: 'Mamirauá Sustainable Development Reserve',
    designation: 'Ramsar Wetland & Sustainable Reserve',
    protected_area_type: 'Sustainable Development Reserve (Ramsar)',
    iucn_category: 'VI',
    country: 'Brazil',
    country_code: 'BR',
    state: 'Amazonas',
    area_km2: 11240,
    total_hectares: 1124000,
    coordinates: { lat: -2.2514, lon: -65.2341 },
    forest_cover_percent: 86.9,
    canopy_loss_year_ha: 215.1,
    active_fires_count: 8,
    threat_index: 52,
    biome: 'Várzea Flooded Freshwater Forest',
    last_analyzed: '2026-09-16T14:10:00Z',
  },
  {
    id: 'area-5',
    wdpa_id: 'WDPA-641',
    name: 'Virunga National Park',
    designation: 'National Park (In Danger)',
    protected_area_type: 'National Park & UNESCO World Heritage (In Danger)',
    iucn_category: 'II',
    country: 'Democratic Republic of Congo',
    country_code: 'CD',
    state: 'North Kivu Province',
    area_km2: 7800,
    total_hectares: 780000,
    coordinates: { lat: -0.0572, lon: 29.5085 },
    forest_cover_percent: 82.1,
    canopy_loss_year_ha: 410.5,
    active_fires_count: 19,
    threat_index: 84,
    biome: 'Albertine Rift Montane Forests & Volcanic Slopes',
    last_analyzed: '2026-09-18T03:00:00Z',
  },
  {
    id: 'area-kanha',
    wdpa_id: 'WDPA-892',
    name: 'Kanha National Park',
    designation: 'Tiger Reserve & National Park',
    protected_area_type: 'Tiger Reserve & National Park (IUCN II)',
    iucn_category: 'II',
    country: 'India',
    country_code: 'IN',
    state: 'Madhya Pradesh',
    area_km2: 940,
    total_hectares: 94000,
    coordinates: { lat: 22.3345, lon: 80.6115 },
    forest_cover_percent: 78.4,
    canopy_loss_year_ha: 31.2,
    active_fires_count: 3,
    threat_index: 34,
    biome: 'Central Deccan Moist Deciduous & Sal Woodlands',
    last_analyzed: '2026-09-18T04:20:00Z',
  },
  {
    id: 'area-bandhavgarh',
    wdpa_id: 'WDPA-896',
    name: 'Bandhavgarh National Park',
    designation: 'Tiger Reserve & National Park',
    protected_area_type: 'Tiger Reserve & National Park (IUCN II)',
    iucn_category: 'II',
    country: 'India',
    country_code: 'IN',
    state: 'Madhya Pradesh',
    area_km2: 1536,
    total_hectares: 153600,
    coordinates: { lat: 23.7042, lon: 80.9995 },
    forest_cover_percent: 71.9,
    canopy_loss_year_ha: 42.6,
    active_fires_count: 5,
    threat_index: 48,
    biome: 'Vindhyan Dry Deciduous & Bamboo Mixed Forest',
    last_analyzed: '2026-09-18T05:10:00Z',
  },
  {
    id: 'area-satpura',
    wdpa_id: 'WDPA-901',
    name: 'Satpura Tiger Reserve',
    designation: 'Tiger Reserve & Biosphere Reserve',
    protected_area_type: 'Tiger Reserve & Biosphere Reserve (IUCN II)',
    iucn_category: 'II',
    country: 'India',
    country_code: 'IN',
    state: 'Madhya Pradesh',
    area_km2: 2133,
    total_hectares: 213300,
    coordinates: { lat: 22.4833, lon: 78.2333 },
    forest_cover_percent: 81.2,
    canopy_loss_year_ha: 38.9,
    active_fires_count: 4,
    threat_index: 39,
    biome: 'Satpura Range Montane Deciduous & Teak Forests',
    last_analyzed: '2026-09-18T03:45:00Z',
  }
];

export const MOCK_HOTSPOTS: ChangeEventHotspot[] = [
  {
    id: 'HS-KANHA-01',
    area_id: 'area-kanha',
    area_name: 'Kanha National Park',
    location_detail: 'North-West Buffer Sector, Mukki Range',
    detected_at: '2026-09-17T06:30:00Z',
    area_ha: 14.8,
    delta_ndvi: -0.52,
    percentage_change: -44.8,
    change_type: 'VEGETATION_LOSS',
    severity: 'CRITICAL',
    confidence_score: 0.96,
    coordinates: { lat: 22.348, lon: 80.625 },
    status: 'NEW',
    sensor: 'Sentinel-2 MSI (10m)',
    previous_condition: 'Intact Primary Moist Sal Canopy (Mean NDVI: 0.79), Dense Crown Cover >85%',
    current_condition: 'High Canopy Disturbance with Fragmented Crown Exposure (Mean NDVI: 0.27)',
    potential_contributing_factors: [
      'Proximity to unprotected peripheral forest corridor (< 450 m)',
      'Linear road/haulage track geometry detected on shortwave infrared (B11/B8)',
      'Gentle slope accessibility (< 6°) allowing vehicular transit',
      'Recent dry season soil moisture deficit observed across sector',
    ],
    related_alerts: [
      {
        id: 'ALT-KANHA-881',
        title: 'Critical Canopy Deficit Detected in Mukki Sector',
        severity: 'CRITICAL',
        timestamp: '2026-09-17T07:15:00Z',
      },
      {
        id: 'ALT-KANHA-879',
        title: 'Linear Ingress Corridor Observed on SWIR Bands',
        severity: 'HIGH',
        timestamp: '2026-09-16T18:40:00Z',
      },
    ],
  },
  {
    id: 'HS-BANDH-02',
    area_id: 'area-bandhavgarh',
    area_name: 'Bandhavgarh National Park',
    location_detail: 'Tala Core Zone, Eastern Boundary',
    detected_at: '2026-09-17T14:45:00Z',
    area_ha: 9.7,
    delta_ndvi: -0.45,
    percentage_change: -37.8,
    change_type: 'URBAN_EXPANSION',
    severity: 'HIGH',
    confidence_score: 0.91,
    coordinates: { lat: 23.718, lon: 81.015 },
    status: 'NEW',
    sensor: 'Sentinel-2 MSI (10m)',
    previous_condition: 'Mixed Deciduous Forest with Bamboo Understory (Mean NDVI: 0.72)',
    current_condition: 'Cleared Clearing with Linear Built Structures (NDBI: +0.28, NDVI: 0.35)',
    potential_contributing_factors: [
      'Contiguous extension from existing rural settlement road network',
      'High NDBI spectral signature indicating compacted soil and impervious materials',
      'Absence of natural topographical barrier along western perimeter',
    ],
    related_alerts: [
      {
        id: 'ALT-BANDH-402',
        title: 'Encroachment Signature Identified near Tala Sector',
        severity: 'HIGH',
        timestamp: '2026-09-17T15:20:00Z',
      },
    ],
  },
  {
    id: 'HS-SATP-03',
    area_id: 'area-satpura',
    area_name: 'Satpura Tiger Reserve',
    location_detail: 'Bori Wildlife Sanctuary Zone, Pachmarhi Slopes',
    detected_at: '2026-09-16T17:20:00Z',
    area_ha: 16.3,
    delta_ndvi: -0.54,
    percentage_change: -46.2,
    change_type: 'FIRE',
    severity: 'CRITICAL',
    confidence_score: 0.97,
    coordinates: { lat: 22.495, lon: 78.249 },
    status: 'NEW',
    sensor: 'VIIRS 375m / S2 MSI',
    previous_condition: 'Dry Deciduous Teak & Bamboo Canopy (Mean NDVI: 0.68)',
    current_condition: 'Active Thermal Scar with Carbon Residuals (Normalized Burn Ratio: -0.42)',
    potential_contributing_factors: [
      'VIIRS active thermal detection (42.6 MW FRP) recorded 6 hours prior to Sentinel-2 pass',
      'Elevated fuel load accumulated following prolonged post-monsoon dry spell',
      'Steep ravines channeling updraft winds',
    ],
    related_alerts: [
      {
        id: 'ALT-SATP-912',
        title: 'Thermal Anomaly (VIIRS 42.6 MW) Confirmed by Sentinel-2 Burn Scar',
        severity: 'CRITICAL',
        timestamp: '2026-09-16T17:45:00Z',
      },
    ],
  },
  {
    id: 'HS-KAZI-04',
    area_id: 'area-2',
    area_name: 'Kaziranga National Park',
    location_detail: 'Bagori Range, Brahmaputra Floodplain',
    detected_at: '2026-09-17T11:05:00Z',
    area_ha: 6.8,
    delta_ndvi: -0.39,
    percentage_change: -33.4,
    change_type: 'WATER_LOSS',
    severity: 'HIGH',
    confidence_score: 0.92,
    coordinates: { lat: 26.589, lon: 93.182 },
    status: 'NEW',
    sensor: 'Sentinel-2 MSI (10m)',
    previous_condition: 'Perennial Wetland Channel & Oxbow Beel (Mean NDWI: +0.52)',
    current_condition: 'Desiccated Silt Splay and Silt Deposition (Mean NDWI: -0.18)',
    potential_contributing_factors: [
      'Post-monsoon river course silt deposition along main river braiding channel',
      'Reduced upstream tributary discharge following dry seasonal cycle',
      'Channel avulsion redirecting flow away from historical oxbow wetland',
    ],
    related_alerts: [
      {
        id: 'ALT-KAZI-304',
        title: 'Oxbow Wetland Desiccation in Bagori Range',
        severity: 'HIGH',
        timestamp: '2026-09-17T12:00:00Z',
      },
    ],
  },
  {
    id: 'HS-SEREN-05',
    area_id: 'area-1',
    area_name: 'Serengeti National Park',
    location_detail: 'Northern Sector, Mara River Basin Corridor',
    detected_at: '2026-09-15T09:15:00Z',
    area_ha: 5.1,
    delta_ndvi: -0.31,
    percentage_change: -24.0,
    change_type: 'OTHER',
    severity: 'MEDIUM',
    confidence_score: 0.84,
    coordinates: { lat: -2.312, lon: 34.814 },
    status: 'VERIFIED',
    sensor: 'Sentinel-2 MSI (10m)',
    previous_condition: 'Acacia Savanna Woodland (Mean NDVI: 0.65)',
    current_condition: 'Thinned Crown Cover with Soil Exposure (Mean NDVI: 0.44)',
    potential_contributing_factors: [
      'High ungulate herd concentration recorded along migration staging area',
      'Localized elephant browse impact on mature acacia stands',
      'Seasonal dry spell accelerating foliage shedding',
    ],
    related_alerts: [
      {
        id: 'ALT-SEREN-112',
        title: 'Moderate Savanna Canopy Thinning in Northern Staging Area',
        severity: 'MEDIUM',
        timestamp: '2026-09-15T10:30:00Z',
      },
    ],
  },
  {
    id: 'HS-YASUN-06',
    area_id: 'area-3',
    area_name: 'Yasuní National Park',
    location_detail: 'Tiputini Biodiversity Sector, Napo River Valley',
    detected_at: '2026-09-16T14:12:00Z',
    area_ha: 8.3,
    delta_ndvi: -0.44,
    percentage_change: -36.2,
    change_type: 'VEGETATION_LOSS',
    severity: 'HIGH',
    confidence_score: 0.89,
    coordinates: { lat: -0.985, lon: -76.012 },
    status: 'NEW',
    sensor: 'Sentinel-2 MSI (10m)',
    previous_condition: 'Dense Multi-Tiered Evergreen Lowland Rainforest (Mean NDVI: 0.84)',
    current_condition: 'Canopy Perforation & Access Corridor (Mean NDVI: 0.46)',
    potential_contributing_factors: [
      'Proximity to historical exploratory seismic cut lines',
      'Linear clearing aligned with regional oil concession access boundary',
      'Rapid canopy opening detected over single 10-day Sentinel-2 revisit cycle',
    ],
    related_alerts: [
      {
        id: 'ALT-YASUN-219',
        title: 'Rainforest Canopy Perforation in Tiputini Sector',
        severity: 'HIGH',
        timestamp: '2026-09-16T15:00:00Z',
      },
    ],
  },
  {
    id: 'HS-MAMIR-07',
    area_id: 'area-4',
    area_name: 'Mamirauá Reserve',
    location_detail: 'Solimões River Flooded Forest Sector',
    detected_at: '2026-09-15T19:40:00Z',
    area_ha: 22.4,
    delta_ndvi: -0.38,
    percentage_change: -31.5,
    change_type: 'WATER_LOSS',
    severity: 'HIGH',
    confidence_score: 0.91,
    coordinates: { lat: -2.261, lon: -65.228 },
    status: 'VERIFIED',
    sensor: 'Landsat 9 OLI-2 (30m)',
    previous_condition: 'Seasonal Várzea Floodplain Water Body (Mean NDWI: +0.48)',
    current_condition: 'Exposed Mudflats and Sediment Bed (Mean NDWI: -0.12)',
    potential_contributing_factors: [
      'Severe regional drought in upper Amazon basin',
      'Early recession of annual flood pulse by 3.5 weeks compared to historical baseline',
      'Elevated water surface temperatures accelerating evaporative loss',
    ],
    related_alerts: [
      {
        id: 'ALT-MAMIR-501',
        title: 'Extensive Várzea Floodplain Desiccation Alert',
        severity: 'HIGH',
        timestamp: '2026-09-15T20:10:00Z',
      },
    ],
  },
  {
    id: 'HS-VIRUN-08',
    area_id: 'area-5',
    area_name: 'Virunga National Park',
    location_detail: 'Southern Sector, Mikeno Gorilla Sector',
    detected_at: '2026-09-17T08:24:00Z',
    area_ha: 14.8,
    delta_ndvi: -0.52,
    percentage_change: -44.8,
    change_type: 'VEGETATION_LOSS',
    severity: 'CRITICAL',
    confidence_score: 0.95,
    coordinates: { lat: -0.082, lon: 29.491 },
    status: 'NEW',
    sensor: 'Sentinel-2 MSI (10m)',
    previous_condition: 'Montane Tropical Rainforest (Mean NDVI: 0.82)',
    current_condition: 'Extensive Canopy Clearance & Charcoal Kiln Footprints (Mean NDVI: 0.31)',
    potential_contributing_factors: [
      'Proximity to vulnerable boundary settlement (< 800 m)',
      'High thermal cluster correlation indicative of illicit charcoal production',
      'Trail density connecting through degraded buffer zones',
    ],
    related_alerts: [
      {
        id: 'ALT-VIRUN-780',
        title: 'Critical Montane Forest Clearance in Mikeno Sector',
        severity: 'CRITICAL',
        timestamp: '2026-09-17T09:00:00Z',
      },
    ],
  },
  {
    id: 'HS-KANHA-09',
    area_id: 'area-kanha',
    area_name: 'Kanha National Park',
    location_detail: 'Kanha Core Plateau, Central Meadow Perimeter',
    detected_at: '2026-09-16T09:10:00Z',
    area_ha: 4.5,
    delta_ndvi: -0.26,
    percentage_change: -21.4,
    change_type: 'OTHER',
    severity: 'LOW',
    confidence_score: 0.78,
    coordinates: { lat: 22.319, lon: 80.598 },
    status: 'VERIFIED',
    sensor: 'Sentinel-2 MSI (10m)',
    previous_condition: 'Open Grassland & Sal Fringe (Mean NDVI: 0.58)',
    current_condition: 'Herbaceous Canopy Reduction (Mean NDVI: 0.44)',
    potential_contributing_factors: [
      'Scheduled controlled cool burn for grassland habitat management by forest department',
      'Seasonal ungulate grazing pressure across plateau meadow',
    ],
    related_alerts: [],
  },
];

export const MOCK_FIRES: FireHotspot[] = [
  {
    id: 'fire-201',
    area_id: 'area-5',
    area_name: 'Virunga National Park',
    lat: -0.091,
    lon: 29.475,
    brightness_kelvin: 348.2,
    frp_mw: 42.6,
    confidence: 96,
    satellite: 'VIIRS',
    timestamp: '2026-09-18T02:15:00Z'
  },
  {
    id: 'fire-202',
    area_id: 'area-3',
    area_name: 'Yasuní National Park',
    lat: -1.021,
    lon: -75.981,
    brightness_kelvin: 332.1,
    frp_mw: 28.1,
    confidence: 88,
    satellite: 'VIIRS',
    timestamp: '2026-09-17T21:40:00Z'
  },
  {
    id: 'fire-203',
    area_id: 'area-1',
    area_name: 'Serengeti National Park',
    lat: -2.298,
    lon: 34.862,
    brightness_kelvin: 318.5,
    frp_mw: 15.3,
    confidence: 79,
    satellite: 'MODIS',
    timestamp: '2026-09-17T17:10:00Z'
  }
];

export const MOCK_SPECIES: WildlifeOccurrence[] = [
  {
    id: 'sp-1',
    area_id: 'area-5',
    species_name: 'Mountain Gorilla',
    scientific_name: 'Gorilla beringei beringei',
    iucn_status: 'EN',
    taxon: 'Mammalia',
    count: 14,
    observed_at: '2026-09-10',
    threat_distance_km: 1.4,
    population_info: '~350 individuals (Virunga subpopulation estimate)',
    census_source: 'Greater Virunga Transboundary Collaboration (GVTC) Survey',
  },
  {
    id: 'sp-2',
    area_id: 'area-2',
    species_name: 'Greater One-Horned Rhinoceros',
    scientific_name: 'Rhinoceros unicornis',
    iucn_status: 'VU',
    taxon: 'Mammalia',
    count: 28,
    observed_at: '2026-09-12',
    threat_distance_km: 3.2,
    population_info: '2,613 individuals (2022 official park census)',
    census_source: 'Assam Forest Department & Wildlife Trust of India Census (March 2022)',
  },
  {
    id: 'sp-3',
    area_id: 'area-3',
    species_name: 'Amazonian Jaguar',
    scientific_name: 'Panthera onca',
    iucn_status: 'NT',
    taxon: 'Mammalia',
    count: 4,
    observed_at: '2026-09-08',
    threat_distance_km: 2.1,
    population_info: 'Density ~2.8 to 4.5 individuals / 100 km² (Camera-trap estimate)',
    census_source: 'Wildlife Conservation Society (WCS) Yasuní Camera Grid Survey',
  },
  {
    id: 'sp-4',
    area_id: 'area-1',
    species_name: 'African Savanna Elephant',
    scientific_name: 'Loxodonta africana',
    iucn_status: 'EN',
    taxon: 'Mammalia',
    count: 52,
    observed_at: '2026-09-15',
    threat_distance_km: 0.8,
    population_info: '~7,000–8,000 individuals (Serengeti-Mara ecosystem)',
    census_source: 'Tanzania Wildlife Research Institute (TAWIRI) Aerial Census 2023',
  },
  {
    id: 'sp-5',
    area_id: 'area-kanha',
    species_name: 'Royal Bengal Tiger',
    scientific_name: 'Panthera tigris tigris',
    iucn_status: 'EN',
    taxon: 'Mammalia',
    count: 18,
    observed_at: '2026-09-14',
    threat_distance_km: 1.2,
    population_info: '105 to 120 individuals (Estimated resident tiger population)',
    census_source: 'Status of Tigers, Co-predators & Prey in India (NTCA / WII 2022)',
  },
  {
    id: 'sp-6',
    area_id: 'area-kanha',
    species_name: 'Hard-Ground Barasingha',
    scientific_name: 'Rucervus duvaucelii branderi',
    iucn_status: 'VU',
    taxon: 'Mammalia',
    count: 64,
    observed_at: '2026-09-11',
    threat_distance_km: 2.5,
    population_info: '~800–950 individuals (Exclusive endemic population in Kanha meadows)',
    census_source: 'Kanha Forest Department Annual Herbivore Census (May 2023)',
  },
  {
    id: 'sp-7',
    area_id: 'area-bandhavgarh',
    species_name: 'Royal Bengal Tiger',
    scientific_name: 'Panthera tigris tigris',
    iucn_status: 'EN',
    taxon: 'Mammalia',
    count: 22,
    observed_at: '2026-09-16',
    threat_distance_km: 0.9,
    population_info: '135 to 165 individuals (Highest documented density in central India)',
    census_source: 'National Tiger Conservation Authority (NTCA) All-India Census 2022',
  },
  {
    id: 'sp-8',
    area_id: 'area-satpura',
    species_name: 'Indian Leopard',
    scientific_name: 'Panthera pardus fusca',
    iucn_status: 'VU',
    taxon: 'Mammalia',
    count: 12,
    observed_at: '2026-09-15',
    threat_distance_km: 1.8,
    population_info: '~240–280 individuals across rugged sandstone gorge corridors',
    census_source: 'Satpura Tiger Reserve Management Plan & Camera Trap Assessment (2023)',
  },
  {
    id: 'sp-9',
    area_id: 'area-satpura',
    species_name: 'Sloth Bear',
    scientific_name: 'Melursus ursinus',
    iucn_status: 'VU',
    taxon: 'Mammalia',
    count: 9,
    observed_at: '2026-09-13',
    threat_distance_km: 2.2,
    population_info: 'Significant core breeding population in central highlands',
    census_source: 'IUCN Bear Specialist Group Field Reports',
  },
  {
    id: 'sp-10',
    area_id: 'area-4',
    species_name: 'Red Uakari Monkey',
    scientific_name: 'Cacajao calvus calvus',
    iucn_status: 'VU',
    taxon: 'Mammalia',
    count: 32,
    observed_at: '2026-09-09',
    threat_distance_km: 1.5,
    population_info: '~15,000 individuals confined to flooded várzea forest canopy',
    census_source: 'Mamirauá Institute for Sustainable Development Primate Survey',
  },
  {
    id: 'sp-11',
    area_id: 'area-4',
    species_name: 'Amazon River Dolphin (Boto)',
    scientific_name: 'Inia geoffrensis',
    iucn_status: 'EN',
    taxon: 'Mammalia',
    count: 15,
    observed_at: '2026-09-12',
    threat_distance_km: 3.0,
    population_info: 'High seasonal density in Auati-Paraná waterways',
    census_source: 'Mamirauá Aquatic Megafauna Monitoring Program',
  },
  {
    id: 'sp-12',
    area_id: 'area-2',
    species_name: 'Wild Water Buffalo',
    scientific_name: 'Bubalus arnee',
    iucn_status: 'EN',
    taxon: 'Mammalia',
    count: 45,
    observed_at: '2026-09-14',
    threat_distance_km: 1.1,
    population_info: '~1,600 individuals (Largest remaining wild population in the world)',
    census_source: 'Kaziranga National Park Wetland & Grassland Census 2022',
  }
];

export const MOCK_ALERTS: AlertNotification[] = [
  {
    id: 'alt-1',
    title: 'Critical Canopy Clearing Detected in Virunga Sector 3',
    message: 'Rapid loss of 14.8 ha detected with ΔNDVI -0.52. High probability of illegal logging near gorilla habitat corridor.',
    severity: 'CRITICAL',
    status: 'UNREAD',
    triggered_at: '2026-09-17T08:35:00Z',
    area_id: 'area-5',
    area_name: 'Virunga National Park',
    hotspot_id: 'hs-101'
  },
  {
    id: 'alt-2',
    title: 'High-Temperature Thermal Anomaly (FRP 42.6 MW)',
    message: 'VIIRS telemetry confirmed active fire front progressing toward dense montane forest canopy.',
    severity: 'CRITICAL',
    status: 'UNREAD',
    triggered_at: '2026-09-18T02:20:00Z',
    area_id: 'area-5',
    area_name: 'Virunga National Park'
  },
  {
    id: 'alt-3',
    title: 'Linear Infrastructure Encroachment in Yasuní',
    message: 'New road spur detected expanding 2.3 km into primary rainforest block with built-up index increase +0.31.',
    severity: 'HIGH',
    status: 'UNREAD',
    triggered_at: '2026-09-16T14:30:00Z',
    area_id: 'area-3',
    area_name: 'Yasuní National Park',
    hotspot_id: 'hs-102'
  },
  {
    id: 'alt-4',
    title: 'Seasonal Lagoon Shrinkage Alert',
    message: 'Mamirauá central flooded forest basin registered NDWI decline of 32% compared to historical September median.',
    severity: 'MEDIUM',
    status: 'ACKNOWLEDGED',
    triggered_at: '2026-09-15T20:00:00Z',
    area_id: 'area-4',
    area_name: 'Mamirauá Reserve',
    hotspot_id: 'hs-103'
  },
  {
    id: 'alt-5',
    title: 'Minor Charcoal Burn Scar Detected',
    message: 'Localized canopy thinning of 5.1 ha verified by Sentinel-2 revisit pass.',
    severity: 'LOW',
    status: 'DISMISSED',
    triggered_at: '2026-09-15T10:00:00Z',
    area_id: 'area-1',
    area_name: 'Serengeti National Park',
    hotspot_id: 'hs-104'
  }
];

export const MOCK_REPORTS: ReportItem[] = [
  {
    id: 'rep-1',
    title: 'Q3 2026 Virunga Habitat Degradation & Fire Threat Audit',
    format: 'GEOPDF',
    date_range: '2026-06-01 to 2026-09-15',
    area_name: 'Virunga National Park',
    file_size_mb: 18.4,
    status: 'READY',
    generated_at: '2026-09-17T12:00:00Z'
  },
  {
    id: 'rep-2',
    title: 'Yasuní National Park Infrastructure Encroachment Survey',
    format: 'GEOPACKAGE',
    date_range: '2026-01-01 to 2026-09-01',
    area_name: 'Yasuní National Park',
    file_size_mb: 42.1,
    status: 'READY',
    generated_at: '2026-09-16T15:30:00Z'
  },
  {
    id: 'rep-3',
    title: 'Serengeti Basin Multi-Year Phenology & Water Availability',
    format: 'CSV',
    date_range: '2020-01-01 to 2026-08-31',
    area_name: 'Serengeti National Park',
    file_size_mb: 4.8,
    status: 'READY',
    generated_at: '2026-09-14T09:10:00Z'
  }
];

export const MOCK_TIMELINE: TimelineDataPoint[] = [
  { date: '2025-10', ndvi: 0.74, baseline: 0.72, waterCoverHa: 4800, fireIncidents: 2, canopyLossHa: 4.1 },
  { date: '2025-11', ndvi: 0.76, baseline: 0.73, waterCoverHa: 5100, fireIncidents: 1, canopyLossHa: 2.8 },
  { date: '2025-12', ndvi: 0.72, baseline: 0.71, waterCoverHa: 4900, fireIncidents: 0, canopyLossHa: 3.5 },
  { date: '2026-01', ndvi: 0.68, baseline: 0.70, waterCoverHa: 4400, fireIncidents: 4, canopyLossHa: 8.2 },
  { date: '2026-02', ndvi: 0.65, baseline: 0.68, waterCoverHa: 4100, fireIncidents: 7, canopyLossHa: 12.4 },
  { date: '2026-03', ndvi: 0.69, baseline: 0.71, waterCoverHa: 4300, fireIncidents: 3, canopyLossHa: 6.9 },
  { date: '2026-04', ndvi: 0.75, baseline: 0.74, waterCoverHa: 5200, fireIncidents: 1, canopyLossHa: 3.1 },
  { date: '2026-05', ndvi: 0.78, baseline: 0.76, waterCoverHa: 5600, fireIncidents: 0, canopyLossHa: 2.4 },
  { date: '2026-06', ndvi: 0.73, baseline: 0.74, waterCoverHa: 5000, fireIncidents: 5, canopyLossHa: 9.6 },
  { date: '2026-07', ndvi: 0.64, baseline: 0.71, waterCoverHa: 4200, fireIncidents: 11, canopyLossHa: 18.5 },
  { date: '2026-08', ndvi: 0.58, baseline: 0.69, waterCoverHa: 3800, fireIncidents: 18, canopyLossHa: 26.2 },
  { date: '2026-09', ndvi: 0.52, baseline: 0.68, waterCoverHa: 3400, fireIncidents: 23, canopyLossHa: 34.8 },
];
