import {
  PublicOverview,
  PublicDemonstrationItem,
  PublicChangeEvent,
} from './public-api';

export const FALLBACK_OVERVIEW: PublicOverview = {
  system_status: 'operational',
  deployment: 'offline-preview',
  version: '1.0.0',
  engine: 'Google Earth Engine & Sentinel-2 L2A',
  demonstration_mode: true,
  is_curated_demo: true,
  disclaimer:
    'Curated satellite telemetry observations computed from Sentinel-2 L2A surface reflectance and Google Dynamic World. Exact incident coordinates are generalized to prevent exposing sensitive wildlife receptors.',
  enabled_methods: ['NDVI_ANOMALY', 'NDWI_WATER_EXTRACTION', 'SPECTRAL_INDEX_CHANGE'],
  monitored_reserves_count: 8,
  total_monitored_area_km2: 48943,
  curated_analyses_count: 14,
  total_detected_events_count: 38,
  data_sources: [
    {
      name: 'Copernicus Sentinel-2',
      provider: 'ESA / Copernicus',
      resolution: '10m / 5-day revisit',
      status: 'operational',
      attribution: 'Contains modified Copernicus Sentinel data',
    },
    {
      name: 'Google Dynamic World',
      provider: 'World Resources Institute / Google',
      resolution: '10m Near Real-Time',
      status: 'operational',
      attribution: 'Open Earth Engine LULC',
    },
    {
      name: 'VIIRS / MODIS Fire Alerts',
      provider: 'NASA FIRMS',
      resolution: '375m / Active thermal',
      status: 'operational',
      attribution: 'NASA Earth Data',
    },
    {
      name: 'OpenStreetMap Hydro & Boundaries',
      provider: 'OSM Contributors',
      resolution: 'Vector Topology',
      status: 'operational',
      attribution: 'ODbL',
    },
  ],
};

export const FALLBACK_DEMOS: PublicDemonstrationItem[] = [
  {
    id: 'demo-pench',
    area_id: 'area-pench',
    area_slug: 'pench-tiger-reserve',
    area_name: 'Pench Tiger Reserve',
    designation: 'Tiger Reserve & National Park',
    country: 'India',
    state: 'Madhya Pradesh',
    area_km2: 1179,
    centroid: { lat: 21.673, lon: 79.302 },
    boundary: {
      type: 'Polygon',
      coordinates: [
        [
          [79.15, 21.55],
          [79.45, 21.55],
          [79.48, 21.80],
          [79.20, 21.82],
          [79.15, 21.55],
        ],
      ],
    },
    baseline_period: { start: '2025-01-01', end: '2025-03-31' },
    comparison_period: { start: '2026-01-01', end: '2026-03-31' },
    status: 'COMPLETED',
    vegetation_loss_ha: 18.4,
    water_change_ha: -6.2,
    event_count: 3,
    is_curated_demo: true,
    read_only: true,
    created_at: '2026-09-18T12:00:00Z',
    disclaimer: 'Demonstration run with generalized coordinates.',
  },
  {
    id: 'demo-tadoba',
    area_id: 'area-tadoba',
    area_slug: 'tadoba-andhari',
    area_name: 'Tadoba-Andhari Tiger Reserve',
    designation: 'Tiger Reserve (IUCN II)',
    country: 'India',
    state: 'Maharashtra',
    area_km2: 1727,
    centroid: { lat: 20.252, lon: 79.334 },
    boundary: {
      type: 'Polygon',
      coordinates: [
        [
          [79.18, 20.10],
          [79.50, 20.12],
          [79.52, 20.42],
          [79.22, 20.40],
          [79.18, 20.10],
        ],
      ],
    },
    baseline_period: { start: '2025-01-15', end: '2025-04-15' },
    comparison_period: { start: '2026-01-15', end: '2026-04-15' },
    status: 'COMPLETED',
    vegetation_loss_ha: 24.1,
    water_change_ha: -11.8,
    event_count: 2,
    is_curated_demo: true,
    read_only: true,
    created_at: '2026-09-18T14:30:00Z',
    disclaimer: 'Demonstration run with generalized coordinates.',
  },
  {
    id: 'demo-sundarbans',
    area_id: 'area-sundarbans',
    area_slug: 'sundarbans-biosphere',
    area_name: 'Sundarbans Biosphere Reserve',
    designation: 'UNESCO World Heritage & Ramsar',
    country: 'India',
    state: 'West Bengal',
    area_km2: 4260,
    centroid: { lat: 21.949, lon: 88.853 },
    boundary: {
      type: 'Polygon',
      coordinates: [
        [
          [88.60, 21.70],
          [89.10, 21.72],
          [89.05, 22.20],
          [88.65, 22.18],
          [88.60, 21.70],
        ],
      ],
    },
    baseline_period: { start: '2024-11-01', end: '2025-02-28' },
    comparison_period: { start: '2025-11-01', end: '2026-02-28' },
    status: 'COMPLETED',
    vegetation_loss_ha: 31.7,
    water_change_ha: 19.4,
    event_count: 2,
    is_curated_demo: true,
    read_only: true,
    created_at: '2026-09-18T16:00:00Z',
    disclaimer: 'Demonstration run with generalized coordinates.',
  },
];

export const FALLBACK_EVENTS: Record<string, PublicChangeEvent[]> = {
  'demo-pench': [
    {
      id: 'EV-PENCH-01',
      analysis_id: 'an-pench-2026',
      change_type: 'VEGETATION_LOSS',
      change_label: 'Canopy Thinning & Extraction Cluster',
      affected_area_ha: 8.6,
      mean_ndvi_change: -0.42,
      valid_pixel_fraction: 0.98,
      priority_score: 0.88,
      priority_band: 'CRITICAL',
      priority_components: { magnitude: 0.85, sensitivity: 0.92, context: 0.88 },
      status: 'UNDER_REVIEW',
      generalized_coordinates: { lat: 21.684, lon: 79.312 },
      generalized_geometry: {
        type: 'Point',
        coordinates: [79.312, 21.684],
      },
      nearest_known_road_distance_m: 340,
      nearest_known_settlement_distance_m: 1420,
      context_source: 'OpenStreetMap Hydro & Transportation Layer',
      method_version: 'v1.4-sentinel2-gee',
      is_curated_demo: true,
      read_only: true,
      security_notice: 'Generalized coordinate point within 500m radius.',
    },
    {
      id: 'EV-PENCH-02',
      analysis_id: 'an-pench-2026',
      change_type: 'WATER_LOSS',
      change_label: 'Ephemeral Water Basin Contraction',
      affected_area_ha: 4.8,
      mean_ndvi_change: null,
      valid_pixel_fraction: 0.95,
      priority_score: 0.72,
      priority_band: 'HIGH',
      priority_components: { magnitude: 0.68, sensitivity: 0.8, context: 0.7 },
      status: 'CONFIRMED',
      generalized_coordinates: { lat: 21.661, lon: 79.288 },
      generalized_geometry: {
        type: 'Point',
        coordinates: [79.288, 21.661],
      },
      nearest_known_road_distance_m: 820,
      nearest_known_settlement_distance_m: 2100,
      context_source: 'OpenStreetMap Hydro & Transportation Layer',
      method_version: 'v1.4-sentinel2-gee',
      is_curated_demo: true,
      read_only: true,
      security_notice: 'Generalized coordinate point within 500m radius.',
    },
    {
      id: 'EV-PENCH-03',
      analysis_id: 'an-pench-2026',
      change_type: 'VEGETATION_LOSS',
      change_label: 'Peripheral Buffer Trail Disturbance',
      affected_area_ha: 5.0,
      mean_ndvi_change: -0.31,
      valid_pixel_fraction: 0.94,
      priority_score: 0.58,
      priority_band: 'MEDIUM',
      priority_components: { magnitude: 0.52, sensitivity: 0.65, context: 0.6 },
      status: 'VERIFIED',
      generalized_coordinates: { lat: 21.705, lon: 79.335 },
      generalized_geometry: {
        type: 'Point',
        coordinates: [79.335, 21.705],
      },
      nearest_known_road_distance_m: 160,
      nearest_known_settlement_distance_m: 880,
      context_source: 'OpenStreetMap Hydro & Transportation Layer',
      method_version: 'v1.4-sentinel2-gee',
      is_curated_demo: true,
      read_only: true,
      security_notice: 'Generalized coordinate point within 500m radius.',
    },
  ],
  'demo-tadoba': [
    {
      id: 'EV-TAD-01',
      analysis_id: 'an-tadoba-2026',
      change_type: 'VEGETATION_LOSS',
      change_label: 'Corridor Canopy Disturbance in Moharli Sector',
      affected_area_ha: 14.2,
      mean_ndvi_change: -0.51,
      valid_pixel_fraction: 0.99,
      priority_score: 0.94,
      priority_band: 'CRITICAL',
      priority_components: { magnitude: 0.92, sensitivity: 0.96, context: 0.95 },
      status: 'UNDER_REVIEW',
      generalized_coordinates: { lat: 20.268, lon: 79.352 },
      generalized_geometry: {
        type: 'Point',
        coordinates: [79.352, 20.268],
      },
      nearest_known_road_distance_m: 290,
      nearest_known_settlement_distance_m: 1100,
      context_source: 'OpenStreetMap Hydro & Transportation Layer',
      method_version: 'v1.4-sentinel2-gee',
      is_curated_demo: true,
      read_only: true,
      security_notice: 'Generalized coordinate point within 500m radius.',
    },
    {
      id: 'EV-TAD-02',
      analysis_id: 'an-tadoba-2026',
      change_type: 'WATER_LOSS',
      change_label: 'Tadoba Lake Reservoir Perimeter Shrinkage',
      affected_area_ha: 9.9,
      mean_ndvi_change: null,
      valid_pixel_fraction: 0.96,
      priority_score: 0.76,
      priority_band: 'HIGH',
      priority_components: { magnitude: 0.75, sensitivity: 0.82, context: 0.72 },
      status: 'VERIFIED',
      generalized_coordinates: { lat: 20.235, lon: 79.318 },
      generalized_geometry: {
        type: 'Point',
        coordinates: [79.318, 20.235],
      },
      nearest_known_road_distance_m: 450,
      nearest_known_settlement_distance_m: 1850,
      context_source: 'OpenStreetMap Hydro & Transportation Layer',
      method_version: 'v1.4-sentinel2-gee',
      is_curated_demo: true,
      read_only: true,
      security_notice: 'Generalized coordinate point within 500m radius.',
    },
  ],
  'demo-sundarbans': [
    {
      id: 'EV-SUN-01',
      analysis_id: 'an-sun-2026',
      change_type: 'VEGETATION_LOSS',
      change_label: 'Tidal Mangrove Edge Dieback & Bank Scour',
      affected_area_ha: 21.3,
      mean_ndvi_change: -0.46,
      valid_pixel_fraction: 0.97,
      priority_score: 0.91,
      priority_band: 'CRITICAL',
      priority_components: { magnitude: 0.9, sensitivity: 0.94, context: 0.89 },
      status: 'VERIFIED',
      generalized_coordinates: { lat: 21.962, lon: 88.874 },
      generalized_geometry: {
        type: 'Point',
        coordinates: [88.874, 21.962],
      },
      nearest_known_road_distance_m: 2400,
      nearest_known_settlement_distance_m: 3200,
      context_source: 'OpenStreetMap Hydro & Transportation Layer',
      method_version: 'v1.4-sentinel2-gee',
      is_curated_demo: true,
      read_only: true,
      security_notice: 'Generalized coordinate point within 500m radius.',
    },
    {
      id: 'EV-SUN-02',
      analysis_id: 'an-sun-2026',
      change_type: 'WATER_LOSS',
      change_label: 'Intertidal Mudflat Hydrological Inundation Shift',
      affected_area_ha: 10.4,
      mean_ndvi_change: null,
      valid_pixel_fraction: 0.93,
      priority_score: 0.69,
      priority_band: 'MEDIUM',
      priority_components: { magnitude: 0.65, sensitivity: 0.75, context: 0.68 },
      status: 'CONFIRMED',
      generalized_coordinates: { lat: 21.928, lon: 88.831 },
      generalized_geometry: {
        type: 'Point',
        coordinates: [88.831, 21.928],
      },
      nearest_known_road_distance_m: 3100,
      nearest_known_settlement_distance_m: 4100,
      context_source: 'OpenStreetMap Hydro & Transportation Layer',
      method_version: 'v1.4-sentinel2-gee',
      is_curated_demo: true,
      read_only: true,
      security_notice: 'Generalized coordinate point within 500m radius.',
    },
  ],
};
